### ISSUE TITLE
Request for the datasets

### ISSUE THREAD

**Issue by hulkima** [liuqidong07/DiffuASR#1]
Thanks for this awesome work! I'd like to reproduce this work, while noticing that there lacks the datasets in this Repo, so could you send the dataset and their pre-process code to me via the email: sdlcmahaokai@163.com. Double thanks for your help!

**Comment by Nickstree** [comment]
Thanks for your great work! I also want to reproduce this work. Would you please send the dataset and their pre-process code to me via the email: [hsnu.nick@gmail.com](url) or share them on the public platform? Thanks a lot!!!

**Comment by liuqidong07** [comment]
Thanks for your interest in our work. Sorry for the late response. Actually, we adopt the same dataset and preprocessing code as one implementation of [SASRec](https://github.com/kang205/SASRec/tree/master). You can refer to that repo. Best.
