### ISSUE TITLE
Lack many necessary models.

### ISSUE THREAD

**Issue by hulkima** [liuqidong07/DiffuASR#2]
Sorry for open a new issue. When I run the given command line: bash ./experiments/diffusion.bash, some bugs occur. That is, it perhaps lack some necessary files in the Repository, such as "trainers.diffusion_trainer". Could you provide these lacked files?

**Comment by liuqidong07** [comment]
Thanks for your interest in our work. Sorry for the late response. We have uploaded the diffusion_trainer. You can find it at https://github.com/liuqidong07/DiffuASR/blob/main/trainers/diffusion_trainer.py. Best
