### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by Traiiicy** [liuqidong07/DiffuASR#4]
Exceptionally great job! 
I'm learning to use diffusion modeling for data enhancement tasks, can you send me your dataset please? I would like to try to reproduce your work. Much appreciated!

**Comment by liuqidong07** [comment]
Thanks for your interest in our work. We adopt the same dataset and preprocessing code as one implementation of [SASRec](https://github.com/kang205/SASRec/tree/master). Best.
